import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync} from 'node:fs';
import test from 'node:test';
let container;
const file='supabase/migrations/20260910_response_rate_report.sql';
const sql=q=>execFileSync('docker',['exec','-i',container,'psql','-h','/tmp','-U','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],{input:q,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();
const call=(email='qa@example.test',uid='00000000-0000-4000-8000-000000000001',start='2026-09-03',end='2026-09-09')=>JSON.parse(sql(`SET request.jwt.claims='${JSON.stringify({sub:uid,email})}';SELECT public.rpc_bao_cao_phan_hoi_mail('${start}','${end}');`));
test.before(()=>{container=execFileSync('docker',['run','-d','--rm','--network','none','--user','postgres','--entrypoint','sh','public.ecr.aws/supabase/postgres:17.6.1.158','-c',"initdb -D /tmp/test-data -A trust --no-locale -E UTF8 >/tmp/init.log && exec postgres -D /tmp/test-data -k /tmp -c listen_addresses=''"],{encoding:'utf8'}).trim();execFileSync('docker',['exec',container,'sh','-c','for i in $(seq 1 50); do pg_isready -h /tmp -U postgres >/dev/null && exit 0; sleep 0.1; done; exit 1']);sql(`
CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$SELECT current_setting('request.jwt.claims',true)::jsonb$$;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(auth.jwt()->>'sub','')::uuid$$;
CREATE TABLE nguoi_dung(email text,vai_tro text,khu_vuc text[],kich_hoat boolean);
INSERT INTO nguoi_dung VALUES ('qa@example.test','QA',ARRAY['C1'],true),('ipc@example.test','IPC',ARRAY['C1'],true),('off@example.test','QA',ARRAY['C1'],false),('empty@example.test','QA','{}',true);
CREATE TABLE su_co(ma_su_co bigint,ma_phong text,khu_vuc text,thuoc_thu_nghiem boolean);
INSERT INTO su_co VALUES (1,'C1.A','C1',false),(2,'Q2.A','Q2',false),(3,'C1.B','C1',false),(4,'C1.C','C1',false),(5,'C1.D','C1',false);
CREATE TABLE email_da_gui(id bigint,loai_email text,trang_thai text,thuoc_thu_nghiem boolean,gui_luc timestamptz,du_lieu jsonb,noi_dung_html text,phan_hoi_smtp jsonb,so_su_co int);
CREATE TABLE ma_token_email(token_hash text,thuoc_thu_nghiem boolean,ma_su_co bigint,hanh_dong text,vai_tro_can text);
CREATE TABLE bms_mail_guard_v18(claim_id int,sent_at timestamptz,created_at timestamptz,state text,test_mode boolean);
CREATE TABLE bms_mail_guard_unit_v18(claim_id int,unit jsonb);
CREATE TABLE bms_mail_delivery_v16(sent_at timestamptz,claimed_at timestamptz,state text,test_mode boolean,message jsonb);
CREATE TABLE lich_su_su_co(ma_su_co bigint,vai_tro text,thoi_diem timestamptz,hanh_dong text,nguon text,thuoc_thu_nghiem boolean);
CREATE FUNCTION bms_mail_hours_v18(text[],timestamptz) RETURNS boolean LANGUAGE sql STABLE AS $$SELECT extract(isodow from $2 AT TIME ZONE 'Asia/Ho_Chi_Minh')<7 AND ($2 AT TIME ZONE 'Asia/Ho_Chi_Minh')::time >= '07:45' AND ($2 AT TIME ZONE 'Asia/Ho_Chi_Minh')::time < '16:45'$$;
INSERT INTO bms_mail_guard_v18 VALUES(1,'2026-09-03 08:00+07',null,'SENT',false),(2,'2026-09-03 20:00+07',null,'SENT',false),(3,'2026-08-27 08:00+07',null,'SENT',false);
INSERT INTO bms_mail_guard_unit_v18 VALUES(1,'{"incident_id":"1","role":"IPC","event_kind":"ACTION"}'),(1,'{"incident_id":"1","role":"IPC","event_kind":"ACTION"}'),(1,'{"incident_id":"2","role":"IPC","event_kind":"ACTION"}'),(1,'{"incident_id":"3","role":"IPC","event_kind":"ACTION"}'),(2,'{"incident_id":"4","role":"MEP","event_kind":"ACTION"}'),(3,'{"incident_id":"5","role":"IPC","event_kind":"ACTION"}');
INSERT INTO lich_su_su_co VALUES(1,'IPC','2026-09-03 09:00+07','ipc_nhan_viec','web',false),(3,'IPC','2026-09-10 09:00+07','ipc_nhan_viec','web',false),(5,'IPC','2026-09-03 09:00+07','ipc_nhan_viec','web',false);
`);if(existsSync(file))sql(readFileSync(file,'utf8'));});
test.after(()=>{if(container)execFileSync('docker',['rm','-f',container],{stdio:'pipe'});});
test('hai tuần, đúng scope, ngoài giờ, dedup và chốt phản hồi từng tuần',()=>{const r=call();assert.equal(r.periods.length,2);assert.deepEqual(r.periods[0].rows.find(x=>x.role==='IPC'),{role:'IPC',denominator:2,responded:1,rate_pct:50});assert.equal(r.periods[1].rows.find(x=>x.role==='IPC').rate_pct,0);assert.equal(r.periods[0].rows.find(x=>x.role==='MEP').rate_pct,null);assert.ok(r.periods[0].details.every(x=>x.ma_phong.startsWith('C1.')));assert.ok(!JSON.stringify(r).includes('token'));});
test('từ chối anon, sai vai, inactive và tài khoản không đăng ký',()=>{for(const [email,uid]of [['qa@example.test',''],['ipc@example.test',undefined],['off@example.test',undefined],['missing@example.test',undefined]])assert.throws(()=>call(email,uid));});
test('khu rỗng không mở rộng quyền',()=>{const r=call('empty@example.test');assert.ok(r.periods.every(p=>p.rows.every(x=>x.denominator===0)));});
test('từ chối kỳ quá dài và kỳ chưa kết thúc',()=>{assert.throws(()=>call(undefined,undefined,'2026-09-01','2026-09-09'));assert.throws(()=>call(undefined,undefined,'2099-09-03','2099-09-09'));});
test('public/anon không được execute',()=>{assert.equal(sql("SELECT has_function_privilege('anon','public.rpc_bao_cao_phan_hoi_mail(date,date)','EXECUTE');"),'f');});
test('v16 gửi ngoài giờ rồi gửi trong giờ chỉ tính một lần, không đếm cùng v18',()=>{sql(`INSERT INTO bms_mail_delivery_v16 VALUES('2026-09-03 20:00+07',null,'SENT',false,'{"role":"MEP","kind":"REMINDER","incidentIds":["4"]}'),('2026-09-04 08:00+07',null,'SENT',false,'{"role":"MEP","kind":"REMINDER","incidentIds":["4"]}'),('2026-09-03 08:00+07',null,'SENT',false,'{"role":"IPC","kind":"REMINDER","incidentIds":["1"]}');`);try{const p=call().periods[0];assert.equal(p.rows.find(x=>x.role==='MEP').denominator,1);assert.equal(p.rows.find(x=>x.role==='IPC').denominator,2);assert.equal(p.details.find(x=>x.role==='MEP').first_sent,'2026-09-04T01:00:00+00:00');}finally{sql('DELETE FROM bms_mail_delivery_v16;');}});
test('legacy chỉ nhận token đúng phiếu/vai và SMTP thành công; không xuất token',()=>{sql(`INSERT INTO email_da_gui VALUES(1,'DIGEST_CANH_BAO','DA_GUI',false,'2026-09-04 08:00+07','{"vai_tro":"QA"}','?sc=1&act=qa_nhan_ra_soat&token=fixture-only','{"accepted":["qa@example.test"],"rejected":[]}',1);INSERT INTO ma_token_email VALUES(encode(sha256(convert_to('fixture-only','UTF8')),'hex'),false,1,'qa_nhan_ra_soat','QA');`);try{let p=call().periods[0];assert.equal(p.rows.find(x=>x.role==='QA').denominator,1);assert.equal(p.has_legacy,true);assert.ok(!JSON.stringify(p).includes('fixture-only'));sql("UPDATE ma_token_email SET vai_tro_can='IPC';");p=call().periods[0];assert.equal(p.rows.find(x=>x.role==='QA').denominator,0);}finally{sql('DELETE FROM email_da_gui;DELETE FROM ma_token_email;');}});
